import compression from "compression";
import cors from "cors";
import express from "express";
import helmet from "helmet";
import { pinoHttp } from "pino-http";
import { env } from "./config/env.js";
import { logger } from "./config/logger.js";
import { errorHandler } from "./middleware/error.js";
import { adminRouter } from "./routes/admin.js";
import { authRouter } from "./routes/auth.js";
import { cartRouter } from "./routes/cart.js";
import { chatRouter } from "./routes/chat.js";
import { checkoutRouter } from "./routes/checkout.js";
import { ordersRouter } from "./routes/orders.js";
import { productsRouter } from "./routes/products.js";
import { sellerRouter } from "./routes/seller.js";
import { webhooksRouter } from "./routes/webhooks.js";
import { uploadsRoot } from "./services/storage.js";

export const app = express();

app.use("/api/webhooks", webhooksRouter);
app.get("/health", (_req, res) => res.json({ ok: true }));
app.use(helmet({ crossOriginResourcePolicy: { policy: "cross-origin" } }));
app.use(cors({ origin: env.FRONTEND_URL, credentials: true }));
app.use(compression());
app.use(pinoHttp({ logger }));
app.use(express.json({ limit: "1mb" }));
app.use("/uploads", express.static(uploadsRoot, { maxAge: "1d" }));

app.use("/api/billing", webhooksRouter);
app.use("/api/products", productsRouter);
app.use("/api/auth", authRouter);
app.use("/api/cart", cartRouter);
app.use("/api/chat", chatRouter);
app.use("/api/checkout", checkoutRouter);
app.use("/api/orders", ordersRouter);
app.use("/api/seller", sellerRouter);
app.use("/api/admin", adminRouter);
app.use(errorHandler);
